"""Update DaycareWaitlist pet_name to allow empty

Revision ID: 29de6c1388f7
Revises: 4fac0e99052f
Create Date: 2025-10-05 07:43:40.829751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29de6c1388f7'
down_revision = '4fac0e99052f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daycare_waitlist', schema=None) as batch_op:
        batch_op.alter_column('pet_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daycare_waitlist', schema=None) as batch_op:
        batch_op.alter_column('pet_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
