"""Fresh database with service_blocks

Revision ID: c44c21251d16
Revises: 
Create Date: 2025-10-04 17:25:40.250271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44c21251d16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('spayed_neutered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('microchipped', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('microchip_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('medical_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vaccination_record_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('vaccination_record_path')
        batch_op.drop_column('photo_path')
        batch_op.drop_column('medical_notes')
        batch_op.drop_column('microchip_number')
        batch_op.drop_column('microchipped')
        batch_op.drop_column('spayed_neutered')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
