"""Add monday wednesday friday fields to daycare_enrollment

Revision ID: f2be576a1519
Revises: 29de6c1388f7
Create Date: 2025-10-05 18:53:42.137263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2be576a1519'
down_revision = '29de6c1388f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daycare_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wednesday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('friday', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daycare_enrollment', schema=None) as batch_op:
        batch_op.drop_column('friday')
        batch_op.drop_column('wednesday')
        batch_op.drop_column('monday')

    # ### end Alembic commands ###
